name: Security - Container Vulnerabilities

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build de l'image Docker (Backend)
        run: docker build -t weave-api:test ./be

      - name: Scan de vulnérabilités (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'weave-api:test'
          format: 'table'
          # On ignore les failles non corrigées ou mineures pour ne pas bloquer tout le temps
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          exit-code: '1' # Fait échouer le pipeline si des failles CRITIQUES sont trouvées
